---
- hosts: webserver
  remote_user: ravi
  become: yes
  become_method: sudo
  tasks:
   - name: disk space utilization
     command: "df -h /"
     register: disk_space
   - debug:
     msg: "{{ disk_space.stdout }}"

