---
- hosts: 192.168.150.139
  tasks:

- name: Installing webservice in webgroup servers
  hosts: 192.168.150.139
  remote_user: ravi
  become: yes
  become_method: sudo
  tasks:
  roles:
   - web
 
  












